### ISSUE TITLE
Changelog / releases?

### ISSUE THREAD

**Issue by mwarkentin** [cloudpassage/jira_halo_issues_sync#62]
Hey @ashmastaflash , now that we're actively using this project, it would be helpful to have an easy way to follow updates and changes as they're made. Any thoughts on adding a changelog / github releases w/ descriptions?

Thanks!

**Comment by ashmastaflash** [comment]
Hey @mwarkentin thanks for the feedback- that's been on my mind and I completely agree.

Stand by...

**Comment by ashmastaflash** [comment]
Hey @mwarkentin v1.0 is out!

Made some performance improvements, love to get your thoughts.

**Comment by mwarkentin** [comment]
@ashmastaflash anything we need to do to get the performance improvements? Or just deploy the updated code?

We've been having some issues I haven't been able to dig into yet, but might be performance related (timeouts) so this is interesting. :)

**Comment by ashmastaflash** [comment]
Just update using code from the master branch, or the v1.0 tag, and you're good to go. No config changes required.  The original code used two initial queries to get active and resolved issues. That's been consolidated into one query, and it makes the whole process much more straightforward.

I'm happy to look at logs or stack traces if you're concerned that it's not working as it should.

**Comment by mwarkentin** [comment]
Going to try to test this out today, but in the meantime, increasing the memory for the lambda from 256 -> 1024 (haven't tried tuning in between yet) seems to have gotten things moving again. Any thoughts if your latest changes might impact that?

**Comment by mwarkentin** [comment]
FWIW, here was the output for a big run after making the update, increasing the memory, and increasing the timeout - I think in the docs it recommended 256MB ram config, maybe worth going to 512?

![](https://s3.amazonaws.com/mwarkentin-snaps/Lambda_Management_Console_2019-04-16_09-09-49.png)
